version: "3.3"
services:
  ui:
    container_name: hotel_ui
    build:
      context: ..
      dockerfile: distribution/Dockerfile-ui
    ports:
      - "8081:80"
    depends_on:
      - api
  api:
    container_name: hotel_api
    build:
      context: ..
      dockerfile: distribution/Dockerfile
    ports:
      - "8080:8090"
