#stage 1
FROM node:latest as node
WORKDIR /app
COPY ./frontend .
RUN npm install
RUN npx ng build
#stage 2
FROM nginx:alpine

COPY ./distribution/nginx-default.conf /etc/nginx/conf.d/default.conf
COPY --from=node /app/dist/hotel-booking /usr/share/nginx/html
